# Generated by Django 5.0.6 on 2026-05-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patient",
            options={"verbose_name": "Patient", "verbose_name_plural": "Patients"},
        ),
        migrations.AlterField(
            model_name="patient",
            name="blood_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="completed",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("Patient", "Patient"), ("Doctor", "Doctor")],
                default="Patient",
                max_length=50,
            ),
        ),
    ]
