# Generated by Django 5.0.6 on 2026-05-18 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical", "0002_alter_patient_options_alter_patient_blood_group_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disease_type", models.CharField(max_length=50)),
                ("input_parameters", models.TextField(blank=True)),
                ("risk_score", models.FloatField(default=0.0)),
                ("risk_level", models.CharField(default="LOW", max_length=50)),
                ("clinical_reasoning", models.TextField(blank=True)),
                ("remedies", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="medical.patient",
                    ),
                ),
            ],
        ),
    ]
