# Generated by Django 5.0.6 on 2026-05-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical", "0003_predictionrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="license_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="medical_proof_file",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
