# Generated by Django 5.0.6 on 2026-06-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical", "0005_pathologyreport_guest_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_file", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("embedding_json", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
